"""Initial migration

Revision ID: 83f32b288ca1
Revises: 
Create Date: 2026-01-10 13:27:42.433276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f32b288ca1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('corridors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_country', sa.Integer(), nullable=True),
    sa.Column('to_country', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_country'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['to_country'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('corridor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_sent', sa.Float(), nullable=False),
    sa.Column('amount_received', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('corridor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('rates')
    op.drop_table('corridors')
    op.drop_table('users')
    op.drop_table('countries')
    # ### end Alembic commands ###
